/**
 * This code was generated by Diez version 10.2.3.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */
import { Color, DropShadow, Font, Point2D, Typograph } from "@diez/prefabs";

const designColors = {
    gray1: Color.rgba(51, 51, 51, 1),
    gray2: Color.rgba(79, 79, 79, 1),
    gray3: Color.rgba(130, 130, 130, 1),
    gray4: Color.rgba(189, 189, 189, 1),
    gray5: Color.rgba(224, 224, 224, 1),
    gray6: Color.rgba(242, 242, 242, 1),
    orange: Color.rgba(242, 153, 74, 1),
    yellow: Color.rgba(242, 201, 76, 1),
    green1: Color.rgba(33, 150, 83, 1),
    green2: Color.rgba(39, 174, 96, 1),
    green3: Color.rgba(111, 207, 151, 1),
    tertiary: Color.rgba(7, 35, 100, 1),
    secondary: Color.rgba(43, 43, 144, 1),
    primary: Color.rgba(69, 115, 238, 1),
    background: Color.rgba(240, 244, 255, 1),
    white: Color.rgba(255, 255, 255, 1),
    red: Color.rgba(235, 87, 87, 1),
    gray11: Color.rgba(51, 51, 51, 1)
};

const designShadows = {
    mdcElevationZ24: new DropShadow({ offset: Point2D.make(0, 9), radius: 46, color: Color.rgba(0, 0, 0, 0.11999999731779099) }),
    mdcElevationZ22: new DropShadow({ offset: Point2D.make(0, 8), radius: 42, color: Color.rgba(0, 0, 0, 0.11999999731779099) }),
    mdcElevationZ20: new DropShadow({ offset: Point2D.make(0, 8), radius: 38, color: Color.rgba(0, 0, 0, 0.11999999731779099) }),
    mdcElevationZ18: new DropShadow({ offset: Point2D.make(0, 7), radius: 34, color: Color.rgba(0, 0, 0, 0.11999999731779099) }),
    mdcElevationZ16: new DropShadow({ offset: Point2D.make(0, 6), radius: 30, color: Color.rgba(0, 0, 0, 0.11999999731779099) }),
    mdcElevationZ14: new DropShadow({ offset: Point2D.make(0, 5), radius: 26, color: Color.rgba(0, 0, 0, 0.11999999731779099) }),
    mdcElevationZ12: new DropShadow({ offset: Point2D.make(0, 5), radius: 22, color: Color.rgba(0, 0, 0, 0.11999999731779099) }),
    mdcElevationZ10: new DropShadow({ offset: Point2D.make(0, 4), radius: 18, color: Color.rgba(0, 0, 0, 0.11999999731779099) }),
    mdcElevationZ8: new DropShadow({ offset: Point2D.make(0, 3), radius: 14, color: Color.rgba(0, 0, 0, 0.11999999731779099) }),
    mdcElevationZ6: new DropShadow({ offset: Point2D.make(0, 1), radius: 18, color: Color.rgba(0, 0, 0, 0.11999999731779099) }),
    mdcElevationZ5: new DropShadow({ offset: Point2D.make(0, 1), radius: 14, color: Color.rgba(0, 0, 0, 0.11999999731779099) }),
    mdcElevationZ4: new DropShadow({ offset: Point2D.make(0, 1), radius: 10, color: Color.rgba(0, 0, 0, 0.11999999731779099) }),
    mdcElevationZ3: new DropShadow({ offset: Point2D.make(0, 1), radius: 8, color: Color.rgba(0, 0, 0, 0.11999999731779099) }),
    mdcElevationZ2: new DropShadow({ offset: Point2D.make(0, 1), radius: 5, color: Color.rgba(0, 0, 0, 0.11999999731779099) }),
    mdcElevationZ1: new DropShadow({ offset: Point2D.make(0, 1), radius: 3, color: Color.rgba(0, 0, 0, 0.11999999731779099) })
};

export const designFonts = {
    Montserrat: {
        SemiBold: Font.fromFile("assets/Design.figma.contents/fonts/Montserrat-SemiBold.otf"),
        Bold: Font.fromFile("assets/Design.figma.contents/fonts/Montserrat-Bold.otf")
    },
    Inter: {
        Medium: Font.fromFile("assets/Design.figma.contents/fonts/Inter-Medium.otf"),
        SemiBold: Font.fromFile("assets/Design.figma.contents/fonts/Inter-SemiBold.otf"),
        Regular: Font.fromFile("assets/Design.figma.contents/fonts/Inter-Regular.otf"),
        Bold: Font.fromFile("assets/Design.figma.contents/fonts/Inter-Bold.otf")
    }
};

const designTypography = {
    fontStyle10: new Typograph({ fontSize: 48, color: Color.rgba(51, 51, 51, 1), font: designFonts.Montserrat.SemiBold }),
    fontStyle9: new Typograph({ fontSize: 36, color: Color.rgba(51, 51, 51, 1), font: designFonts.Montserrat.Bold }),
    fontStyle8: new Typograph({ fontSize: 32, color: Color.rgba(51, 51, 51, 1), font: designFonts.Inter.Medium }),
    fontStyle7: new Typograph({ fontSize: 24, color: Color.rgba(51, 51, 51, 1), font: designFonts.Inter.SemiBold }),
    fontStyle4: new Typograph({ fontSize: 16, color: Color.rgba(51, 51, 51, 1), font: designFonts.Inter.Regular }),
    fontStyle3: new Typograph({ fontSize: 14, color: Color.rgba(51, 51, 51, 1), font: designFonts.Inter.SemiBold }),
    fontStyle2: new Typograph({ fontSize: 12, color: Color.rgba(51, 51, 51, 1), font: designFonts.Inter.Medium }),
    fontStyle1: new Typograph({ fontSize: 10, color: Color.rgba(51, 51, 51, 1), font: designFonts.Inter.Regular }),
    fontStyle12: new Typograph({ fontSize: 96, color: Color.rgba(51, 51, 51, 1), font: designFonts.Montserrat.SemiBold }),
    fontStyle11: new Typograph({ fontSize: 64, color: Color.rgba(51, 51, 51, 1), font: designFonts.Montserrat.Bold }),
    fontStyle6: new Typograph({ fontSize: 20, color: Color.rgba(51, 51, 51, 1), font: designFonts.Inter.Medium }),
    fontStyle5: new Typograph({ fontSize: 18, color: Color.rgba(51, 51, 51, 1), font: designFonts.Inter.Bold })
};

export const designTokens = {
    colors: designColors,
    shadows: designShadows,
    typography: designTypography
};
