"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
/**
 * This code was generated by Diez version 10.3.0.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */
const prefabs_1 = require("@diez/prefabs");
const designColors = {
    gray1: prefabs_1.Color.rgba(51, 51, 51, 1),
    gray2: prefabs_1.Color.rgba(79, 79, 79, 1),
    gray3: prefabs_1.Color.rgba(130, 130, 130, 1),
    gray4: prefabs_1.Color.rgba(189, 189, 189, 1),
    gray5: prefabs_1.Color.rgba(224, 224, 224, 1),
    gray6: prefabs_1.Color.rgba(242, 242, 242, 1),
    orange: prefabs_1.Color.rgba(242, 153, 74, 1),
    yellow: prefabs_1.Color.rgba(242, 201, 76, 1),
    green1: prefabs_1.Color.rgba(33, 150, 83, 1),
    green2: prefabs_1.Color.rgba(39, 174, 96, 1),
    green3: prefabs_1.Color.rgba(111, 207, 151, 1),
    tertiary: prefabs_1.Color.rgba(7, 35, 100, 1),
    secondary: prefabs_1.Color.rgba(43, 43, 144, 1),
    primary: prefabs_1.Color.rgba(69, 115, 238, 1),
    background: prefabs_1.Color.rgba(240, 244, 255, 1),
    white: prefabs_1.Color.rgba(255, 255, 255, 1),
    red: prefabs_1.Color.rgba(235, 87, 87, 1),
    gray11: prefabs_1.Color.rgba(51, 51, 51, 1)
};
const designShadows = {
    mdcElevationZ24: new prefabs_1.DropShadow({ offset: prefabs_1.Point2D.make(0, 9), radius: 46, color: prefabs_1.Color.rgba(0, 0, 0, 0.11999999731779099) }),
    mdcElevationZ22: new prefabs_1.DropShadow({ offset: prefabs_1.Point2D.make(0, 8), radius: 42, color: prefabs_1.Color.rgba(0, 0, 0, 0.11999999731779099) }),
    mdcElevationZ20: new prefabs_1.DropShadow({ offset: prefabs_1.Point2D.make(0, 8), radius: 38, color: prefabs_1.Color.rgba(0, 0, 0, 0.11999999731779099) }),
    mdcElevationZ18: new prefabs_1.DropShadow({ offset: prefabs_1.Point2D.make(0, 7), radius: 34, color: prefabs_1.Color.rgba(0, 0, 0, 0.11999999731779099) }),
    mdcElevationZ16: new prefabs_1.DropShadow({ offset: prefabs_1.Point2D.make(0, 6), radius: 30, color: prefabs_1.Color.rgba(0, 0, 0, 0.11999999731779099) }),
    mdcElevationZ14: new prefabs_1.DropShadow({ offset: prefabs_1.Point2D.make(0, 5), radius: 26, color: prefabs_1.Color.rgba(0, 0, 0, 0.11999999731779099) }),
    mdcElevationZ12: new prefabs_1.DropShadow({ offset: prefabs_1.Point2D.make(0, 5), radius: 22, color: prefabs_1.Color.rgba(0, 0, 0, 0.11999999731779099) }),
    mdcElevationZ10: new prefabs_1.DropShadow({ offset: prefabs_1.Point2D.make(0, 4), radius: 18, color: prefabs_1.Color.rgba(0, 0, 0, 0.11999999731779099) }),
    mdcElevationZ8: new prefabs_1.DropShadow({ offset: prefabs_1.Point2D.make(0, 3), radius: 14, color: prefabs_1.Color.rgba(0, 0, 0, 0.11999999731779099) }),
    mdcElevationZ6: new prefabs_1.DropShadow({ offset: prefabs_1.Point2D.make(0, 1), radius: 18, color: prefabs_1.Color.rgba(0, 0, 0, 0.11999999731779099) }),
    mdcElevationZ5: new prefabs_1.DropShadow({ offset: prefabs_1.Point2D.make(0, 1), radius: 14, color: prefabs_1.Color.rgba(0, 0, 0, 0.11999999731779099) }),
    mdcElevationZ4: new prefabs_1.DropShadow({ offset: prefabs_1.Point2D.make(0, 1), radius: 10, color: prefabs_1.Color.rgba(0, 0, 0, 0.11999999731779099) }),
    mdcElevationZ3: new prefabs_1.DropShadow({ offset: prefabs_1.Point2D.make(0, 1), radius: 8, color: prefabs_1.Color.rgba(0, 0, 0, 0.11999999731779099) }),
    mdcElevationZ2: new prefabs_1.DropShadow({ offset: prefabs_1.Point2D.make(0, 1), radius: 5, color: prefabs_1.Color.rgba(0, 0, 0, 0.11999999731779099) }),
    mdcElevationZ1: new prefabs_1.DropShadow({ offset: prefabs_1.Point2D.make(0, 1), radius: 3, color: prefabs_1.Color.rgba(0, 0, 0, 0.11999999731779099) })
};
exports.designFonts = {
    Montserrat: {
        SemiBold: prefabs_1.Font.fromFile("assets/Design.figma.contents/fonts/Montserrat-SemiBold.ttf"),
        Bold: prefabs_1.Font.fromFile("assets/Design.figma.contents/fonts/Montserrat-Bold.ttf")
    },
    Inter: {
        Medium: prefabs_1.Font.fromFile("assets/Design.figma.contents/fonts/Inter-Medium.otf"),
        SemiBold: prefabs_1.Font.fromFile("assets/Design.figma.contents/fonts/Inter-SemiBold.otf"),
        Regular: prefabs_1.Font.fromFile("assets/Design.figma.contents/fonts/Inter-Regular.otf"),
        Bold: prefabs_1.Font.fromFile("assets/Design.figma.contents/fonts/Inter-Bold.otf")
    }
};
const designTypography = {
    fontStyle10: new prefabs_1.Typograph({ letterSpacing: 0, fontSize: 48, lineHeight: 56.25, color: prefabs_1.Color.rgba(51, 51, 51, 1), font: exports.designFonts.Montserrat.SemiBold }),
    fontStyle9: new prefabs_1.Typograph({ letterSpacing: 0.25, fontSize: 36, lineHeight: 20, color: prefabs_1.Color.rgba(51, 51, 51, 1), font: exports.designFonts.Montserrat.Bold }),
    fontStyle8: new prefabs_1.Typograph({ letterSpacing: 0.25, fontSize: 32, lineHeight: 20, color: prefabs_1.Color.rgba(51, 51, 51, 1), font: exports.designFonts.Inter.Medium }),
    fontStyle7: new prefabs_1.Typograph({ letterSpacing: 0.25, fontSize: 24, lineHeight: 36, color: prefabs_1.Color.rgba(51, 51, 51, 1), font: exports.designFonts.Inter.SemiBold }),
    fontStyle4: new prefabs_1.Typograph({ letterSpacing: 0.25, fontSize: 16, lineHeight: 20, color: prefabs_1.Color.rgba(51, 51, 51, 1), font: exports.designFonts.Inter.Regular }),
    fontStyle3: new prefabs_1.Typograph({ letterSpacing: 0.315, fontSize: 14, lineHeight: 16.40625, color: prefabs_1.Color.rgba(51, 51, 51, 1), font: exports.designFonts.Inter.SemiBold }),
    fontStyle2: new prefabs_1.Typograph({ letterSpacing: 0.4000000059604645, fontSize: 12, lineHeight: 16, color: prefabs_1.Color.rgba(51, 51, 51, 1), font: exports.designFonts.Inter.Medium }),
    fontStyle1: new prefabs_1.Typograph({ letterSpacing: 1, fontSize: 10, lineHeight: 16, color: prefabs_1.Color.rgba(51, 51, 51, 1), font: exports.designFonts.Inter.Regular }),
    fontStyle12: new prefabs_1.Typograph({ letterSpacing: -1.5, fontSize: 96, lineHeight: 112.5, color: prefabs_1.Color.rgba(51, 51, 51, 1), font: exports.designFonts.Montserrat.SemiBold }),
    fontStyle11: new prefabs_1.Typograph({ letterSpacing: 0, fontSize: 64, lineHeight: 75, color: prefabs_1.Color.rgba(51, 51, 51, 1), font: exports.designFonts.Montserrat.Bold }),
    fontStyle6: new prefabs_1.Typograph({ letterSpacing: 0.5, fontSize: 20, lineHeight: 20, color: prefabs_1.Color.rgba(51, 51, 51, 1), font: exports.designFonts.Inter.Medium }),
    fontStyle5: new prefabs_1.Typograph({ letterSpacing: 0.5, fontSize: 18, lineHeight: 20, color: prefabs_1.Color.rgba(51, 51, 51, 1), font: exports.designFonts.Inter.Bold })
};
exports.designTokens = {
    colors: designColors,
    shadows: designShadows,
    typography: designTypography
};
//# sourceMappingURL=Design.figma.js.map