"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
/**
 * This code was generated by Diez version 10.2.3.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */
const prefabs_1 = require("@diez/prefabs");
const designColors = {
    gray1: prefabs_1.Color.rgba(51, 51, 51, 1),
    gray2: prefabs_1.Color.rgba(79, 79, 79, 1),
    gray3: prefabs_1.Color.rgba(130, 130, 130, 1),
    gray4: prefabs_1.Color.rgba(189, 189, 189, 1),
    gray5: prefabs_1.Color.rgba(224, 224, 224, 1),
    gray6: prefabs_1.Color.rgba(242, 242, 242, 1),
    orange: prefabs_1.Color.rgba(242, 153, 74, 1),
    yellow: prefabs_1.Color.rgba(242, 201, 76, 1),
    green1: prefabs_1.Color.rgba(33, 150, 83, 1),
    green2: prefabs_1.Color.rgba(39, 174, 96, 1),
    green3: prefabs_1.Color.rgba(111, 207, 151, 1),
    tertiary: prefabs_1.Color.rgba(7, 35, 100, 1),
    secondary: prefabs_1.Color.rgba(43, 43, 144, 1),
    primary: prefabs_1.Color.rgba(69, 115, 238, 1),
    background: prefabs_1.Color.rgba(240, 244, 255, 1),
    white: prefabs_1.Color.rgba(255, 255, 255, 1),
    red: prefabs_1.Color.rgba(235, 87, 87, 1),
    gray11: prefabs_1.Color.rgba(51, 51, 51, 1),
    gray12: prefabs_1.Color.rgba(51, 51, 51, 1)
};
const designShadows = {
    mdcElevationZ24: new prefabs_1.DropShadow({ offset: prefabs_1.Point2D.make(0, 9), radius: 46, color: prefabs_1.Color.rgba(0, 0, 0, 0.11999999731779099) }),
    mdcElevationZ22: new prefabs_1.DropShadow({ offset: prefabs_1.Point2D.make(0, 8), radius: 42, color: prefabs_1.Color.rgba(0, 0, 0, 0.11999999731779099) }),
    mdcElevationZ20: new prefabs_1.DropShadow({ offset: prefabs_1.Point2D.make(0, 8), radius: 38, color: prefabs_1.Color.rgba(0, 0, 0, 0.11999999731779099) }),
    mdcElevationZ18: new prefabs_1.DropShadow({ offset: prefabs_1.Point2D.make(0, 7), radius: 34, color: prefabs_1.Color.rgba(0, 0, 0, 0.11999999731779099) }),
    mdcElevationZ16: new prefabs_1.DropShadow({ offset: prefabs_1.Point2D.make(0, 6), radius: 30, color: prefabs_1.Color.rgba(0, 0, 0, 0.11999999731779099) }),
    mdcElevationZ14: new prefabs_1.DropShadow({ offset: prefabs_1.Point2D.make(0, 5), radius: 26, color: prefabs_1.Color.rgba(0, 0, 0, 0.11999999731779099) }),
    mdcElevationZ12: new prefabs_1.DropShadow({ offset: prefabs_1.Point2D.make(0, 5), radius: 22, color: prefabs_1.Color.rgba(0, 0, 0, 0.11999999731779099) }),
    mdcElevationZ10: new prefabs_1.DropShadow({ offset: prefabs_1.Point2D.make(0, 4), radius: 18, color: prefabs_1.Color.rgba(0, 0, 0, 0.11999999731779099) }),
    mdcElevationZ8: new prefabs_1.DropShadow({ offset: prefabs_1.Point2D.make(0, 3), radius: 14, color: prefabs_1.Color.rgba(0, 0, 0, 0.11999999731779099) }),
    mdcElevationZ6: new prefabs_1.DropShadow({ offset: prefabs_1.Point2D.make(0, 1), radius: 18, color: prefabs_1.Color.rgba(0, 0, 0, 0.11999999731779099) }),
    mdcElevationZ5: new prefabs_1.DropShadow({ offset: prefabs_1.Point2D.make(0, 1), radius: 14, color: prefabs_1.Color.rgba(0, 0, 0, 0.11999999731779099) }),
    mdcElevationZ4: new prefabs_1.DropShadow({ offset: prefabs_1.Point2D.make(0, 1), radius: 10, color: prefabs_1.Color.rgba(0, 0, 0, 0.11999999731779099) }),
    mdcElevationZ3: new prefabs_1.DropShadow({ offset: prefabs_1.Point2D.make(0, 1), radius: 8, color: prefabs_1.Color.rgba(0, 0, 0, 0.11999999731779099) }),
    mdcElevationZ2: new prefabs_1.DropShadow({ offset: prefabs_1.Point2D.make(0, 1), radius: 5, color: prefabs_1.Color.rgba(0, 0, 0, 0.11999999731779099) }),
    mdcElevationZ1: new prefabs_1.DropShadow({ offset: prefabs_1.Point2D.make(0, 1), radius: 3, color: prefabs_1.Color.rgba(0, 0, 0, 0.11999999731779099) })
};
exports.designFonts = {
    Montserrat: {
        SemiBold: prefabs_1.Font.fromFile("assets/Design.figma.contents/fonts/Montserrat-SemiBold.otf"),
        Bold: prefabs_1.Font.fromFile("assets/Design.figma.contents/fonts/Montserrat-Bold.otf")
    },
    Inter: {
        Medium: prefabs_1.Font.fromFile("assets/Design.figma.contents/fonts/Inter-Medium.otf"),
        SemiBold: prefabs_1.Font.fromFile("assets/Design.figma.contents/fonts/Inter-SemiBold.otf"),
        Regular: prefabs_1.Font.fromFile("assets/Design.figma.contents/fonts/Inter-Regular.otf"),
        Bold: prefabs_1.Font.fromFile("assets/Design.figma.contents/fonts/Inter-Bold.otf")
    }
};
const designTypography = {
    fontStyle10: new prefabs_1.Typograph({ fontSize: 48, color: prefabs_1.Color.rgba(51, 51, 51, 1), font: exports.designFonts.Montserrat.SemiBold }),
    fontStyle9: new prefabs_1.Typograph({ fontSize: 36, color: prefabs_1.Color.rgba(51, 51, 51, 1), font: exports.designFonts.Montserrat.Bold }),
    fontStyle8: new prefabs_1.Typograph({ fontSize: 32, color: prefabs_1.Color.rgba(51, 51, 51, 1), font: exports.designFonts.Inter.Medium }),
    fontStyle7: new prefabs_1.Typograph({ fontSize: 24, color: prefabs_1.Color.rgba(51, 51, 51, 1), font: exports.designFonts.Inter.SemiBold }),
    fontStyle4: new prefabs_1.Typograph({ fontSize: 16, color: prefabs_1.Color.rgba(51, 51, 51, 1), font: exports.designFonts.Inter.Regular }),
    fontStyle3: new prefabs_1.Typograph({ fontSize: 14, color: prefabs_1.Color.rgba(51, 51, 51, 1), font: exports.designFonts.Inter.SemiBold }),
    fontStyle2: new prefabs_1.Typograph({ fontSize: 12, color: prefabs_1.Color.rgba(51, 51, 51, 1), font: exports.designFonts.Inter.Medium }),
    fontStyle1: new prefabs_1.Typograph({ fontSize: 10, color: prefabs_1.Color.rgba(51, 51, 51, 1), font: exports.designFonts.Inter.Regular }),
    fontStyle12: new prefabs_1.Typograph({ fontSize: 96, color: prefabs_1.Color.rgba(51, 51, 51, 1), font: exports.designFonts.Montserrat.SemiBold }),
    fontStyle11: new prefabs_1.Typograph({ fontSize: 64, color: prefabs_1.Color.rgba(51, 51, 51, 1), font: exports.designFonts.Montserrat.Bold }),
    fontStyle6: new prefabs_1.Typograph({ fontSize: 20, color: prefabs_1.Color.rgba(51, 51, 51, 1), font: exports.designFonts.Inter.Medium }),
    fontStyle5: new prefabs_1.Typograph({ fontSize: 18, color: prefabs_1.Color.rgba(51, 51, 51, 1), font: exports.designFonts.Inter.Bold })
};
exports.designComponentsFiles = {
    iconTest: new prefabs_1.File({ src: "assets/Design.figma.contents/components/IconTest.png" }),
    iconTest2x: new prefabs_1.File({ src: "assets/Design.figma.contents/components/IconTest@2x.png" }),
    iconTest3x: new prefabs_1.File({ src: "assets/Design.figma.contents/components/IconTest@3x.png" }),
    iconTest4x: new prefabs_1.File({ src: "assets/Design.figma.contents/components/IconTest@4x.png" }),
    iconStudent: new prefabs_1.File({ src: "assets/Design.figma.contents/components/IconStudent.png" }),
    iconStudent2x: new prefabs_1.File({ src: "assets/Design.figma.contents/components/IconStudent@2x.png" }),
    iconStudent3x: new prefabs_1.File({ src: "assets/Design.figma.contents/components/IconStudent@3x.png" }),
    iconStudent4x: new prefabs_1.File({ src: "assets/Design.figma.contents/components/IconStudent@4x.png" }),
    iconPerson: new prefabs_1.File({ src: "assets/Design.figma.contents/components/IconPerson.png" }),
    iconPerson2x: new prefabs_1.File({ src: "assets/Design.figma.contents/components/IconPerson@2x.png" }),
    iconPerson3x: new prefabs_1.File({ src: "assets/Design.figma.contents/components/IconPerson@3x.png" }),
    iconPerson4x: new prefabs_1.File({ src: "assets/Design.figma.contents/components/IconPerson@4x.png" }),
    iconDiagram: new prefabs_1.File({ src: "assets/Design.figma.contents/components/IconDiagram.png" }),
    iconDiagram2x: new prefabs_1.File({ src: "assets/Design.figma.contents/components/IconDiagram@2x.png" }),
    iconDiagram3x: new prefabs_1.File({ src: "assets/Design.figma.contents/components/IconDiagram@3x.png" }),
    iconDiagram4x: new prefabs_1.File({ src: "assets/Design.figma.contents/components/IconDiagram@4x.png" }),
    iconSettings: new prefabs_1.File({ src: "assets/Design.figma.contents/components/IconSettings.png" }),
    iconSettings2x: new prefabs_1.File({ src: "assets/Design.figma.contents/components/IconSettings@2x.png" }),
    iconSettings3x: new prefabs_1.File({ src: "assets/Design.figma.contents/components/IconSettings@3x.png" }),
    iconSettings4x: new prefabs_1.File({ src: "assets/Design.figma.contents/components/IconSettings@4x.png" }),
    iconFilter: new prefabs_1.File({ src: "assets/Design.figma.contents/components/IconFilter.png" }),
    iconFilter2x: new prefabs_1.File({ src: "assets/Design.figma.contents/components/IconFilter@2x.png" }),
    iconFilter3x: new prefabs_1.File({ src: "assets/Design.figma.contents/components/IconFilter@3x.png" }),
    iconFilter4x: new prefabs_1.File({ src: "assets/Design.figma.contents/components/IconFilter@4x.png" }),
    iconHelp: new prefabs_1.File({ src: "assets/Design.figma.contents/components/IconHelp.png" }),
    iconHelp2x: new prefabs_1.File({ src: "assets/Design.figma.contents/components/IconHelp@2x.png" }),
    iconHelp3x: new prefabs_1.File({ src: "assets/Design.figma.contents/components/IconHelp@3x.png" }),
    iconHelp4x: new prefabs_1.File({ src: "assets/Design.figma.contents/components/IconHelp@4x.png" }),
    iconWarning: new prefabs_1.File({ src: "assets/Design.figma.contents/components/IconWarning.png" }),
    iconWarning2x: new prefabs_1.File({ src: "assets/Design.figma.contents/components/IconWarning@2x.png" }),
    iconWarning3x: new prefabs_1.File({ src: "assets/Design.figma.contents/components/IconWarning@3x.png" }),
    iconWarning4x: new prefabs_1.File({ src: "assets/Design.figma.contents/components/IconWarning@4x.png" }),
    iconSearch: new prefabs_1.File({ src: "assets/Design.figma.contents/components/IconSearch.png" }),
    iconSearch2x: new prefabs_1.File({ src: "assets/Design.figma.contents/components/IconSearch@2x.png" }),
    iconSearch3x: new prefabs_1.File({ src: "assets/Design.figma.contents/components/IconSearch@3x.png" }),
    iconSearch4x: new prefabs_1.File({ src: "assets/Design.figma.contents/components/IconSearch@4x.png" }),
    iconDownload: new prefabs_1.File({ src: "assets/Design.figma.contents/components/IconDownload.png" }),
    iconDownload2x: new prefabs_1.File({ src: "assets/Design.figma.contents/components/IconDownload@2x.png" }),
    iconDownload3x: new prefabs_1.File({ src: "assets/Design.figma.contents/components/IconDownload@3x.png" }),
    iconDownload4x: new prefabs_1.File({ src: "assets/Design.figma.contents/components/IconDownload@4x.png" }),
    iconListSize: new prefabs_1.File({ src: "assets/Design.figma.contents/components/IconListSize.png" }),
    iconListSize2x: new prefabs_1.File({ src: "assets/Design.figma.contents/components/IconListSize@2x.png" }),
    iconListSize3x: new prefabs_1.File({ src: "assets/Design.figma.contents/components/IconListSize@3x.png" }),
    iconListSize4x: new prefabs_1.File({ src: "assets/Design.figma.contents/components/IconListSize@4x.png" }),
    iconNext: new prefabs_1.File({ src: "assets/Design.figma.contents/components/IconNext.png" }),
    iconNext2x: new prefabs_1.File({ src: "assets/Design.figma.contents/components/IconNext@2x.png" }),
    iconNext3x: new prefabs_1.File({ src: "assets/Design.figma.contents/components/IconNext@3x.png" }),
    iconNext4x: new prefabs_1.File({ src: "assets/Design.figma.contents/components/IconNext@4x.png" })
};
exports.designComponents = {
    iconTest: prefabs_1.Image.responsive("assets/Design.figma.contents/components/IconTest.png", 24, 24),
    iconStudent: prefabs_1.Image.responsive("assets/Design.figma.contents/components/IconStudent.png", 24, 24),
    iconPerson: prefabs_1.Image.responsive("assets/Design.figma.contents/components/IconPerson.png", 24, 24),
    iconDiagram: prefabs_1.Image.responsive("assets/Design.figma.contents/components/IconDiagram.png", 24, 24),
    iconSettings: prefabs_1.Image.responsive("assets/Design.figma.contents/components/IconSettings.png", 24, 24),
    iconFilter: prefabs_1.Image.responsive("assets/Design.figma.contents/components/IconFilter.png", 24, 24),
    iconHelp: prefabs_1.Image.responsive("assets/Design.figma.contents/components/IconHelp.png", 24, 24),
    iconWarning: prefabs_1.Image.responsive("assets/Design.figma.contents/components/IconWarning.png", 24, 24),
    iconSearch: prefabs_1.Image.responsive("assets/Design.figma.contents/components/IconSearch.png", 24, 24),
    iconDownload: prefabs_1.Image.responsive("assets/Design.figma.contents/components/IconDownload.png", 24, 24),
    iconListSize: prefabs_1.Image.responsive("assets/Design.figma.contents/components/IconListSize.png", 24, 24),
    iconNext: prefabs_1.Image.responsive("assets/Design.figma.contents/components/IconNext.png", 24, 24)
};
exports.designTokens = {
    colors: designColors,
    shadows: designShadows,
    typography: designTypography
};
//# sourceMappingURL=Design.figma.js.map